-- Auto-generated by scripts/generate_seed_sql.ts
-- Inserts task_templates (one row per template in src/lib/data/seed.ts)
-- and one pending task_instance per template for today.
-- Idempotency: run this exactly once. Re-running will create duplicates.

begin;

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom I — Sink Zone', 'cleaning', 8, '09:00',
  'Zone A — The Sink.

Clean what you affect. Rinse residue away. Wipe stubborn spots. Dry hands on the towel. Sink visually clean.',
  ARRAY['Rinse residue away', 'Wipe stubborn spots', 'Dry hands on the towel', 'Sink visually clean']::text[],
  0, 0.95, 0
from public.rooms r where r.name = 'Bathroom I';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom I — Toilet Zone', 'cleaning', 6, '09:00',
  'Zone B — The Toilet.

Wipe the seat with a wet wipe. Brush the bowl until clean. Bin the wipe below. Ready for next user.',
  ARRAY['Wipe seat with wet wipe', 'Brush bowl until clean', 'Bin the wipe below', 'Ready for next user']::text[],
  -0.9, 0.85, -0.63
from public.rooms r where r.name = 'Bathroom I';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom I — Shower Zone', 'cleaning', 8, '09:00',
  'Zone C — The Shower.

Rinse everything to drain. Clear the drain filter. Squeegee the glass. Hang the towel fully open.',
  ARRAY['Rinse everything to drain', 'Clear the drain filter', 'Squeegee the glass', 'Hang towel fully open']::text[],
  0, 0.6, 0.57
from public.rooms r where r.name = 'Bathroom I';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom I — Cupboard III (Towels & Medicine)', 'supplies', 10, '10:00',
  'THE RULE — every item returns to its assigned shelf, immediately after use.

Top to bottom: Towels (folded, fully dry) · Medicine (grouped by type) · First Aid (front of shelf, always grabbable) · Tote bags (folded flat) · Canvas bags (stacked, not slumped).

If a towel is damp → hang it to dry first, then fold and store. If medicine is expired → remove and dispose at a pharmacy. If bags slump → empty, refold, restack.',
  ARRAY['Towels on the top shelf — folded, fully dry', 'Medicine grouped by type', 'First aid at the front, grabbable', 'Tote bags folded flat', 'Canvas bags stacked, not slumped', 'No expired medicine on the shelf']::text[],
  1.03, 1.4, -0.5
from public.rooms r where r.name = 'Bathroom I';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom II — Sink Zone', 'cleaning', 8, '09:00',
  'Zone A — The Sink. Rinse · Wipe · Dry · Visually clean.',
  ARRAY['Rinse residue away', 'Wipe stubborn spots', 'Dry hands on the towel', 'Sink visually clean']::text[],
  0, 0.95, 0
from public.rooms r where r.name = 'Bathroom II';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom II — Toilet Zone', 'cleaning', 6, '09:00',
  'Zone B — The Toilet. Wipe seat · Brush bowl · Bin the wipe · Ready for next user.',
  ARRAY['Wipe seat with wet wipe', 'Brush bowl until clean', 'Bin the wipe below', 'Ready for next user']::text[],
  -0.87, 0.85, -0.56
from public.rooms r where r.name = 'Bathroom II';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom II — Shower Zone', 'cleaning', 8, '09:00',
  'Zone C — The Shower. Rinse · Clear the drain · Squeegee glass · Hang towel.',
  ARRAY['Rinse everything to drain', 'Clear the drain filter', 'Squeegee the glass', 'Hang towel fully open']::text[],
  0, 0.6, 0.5
from public.rooms r where r.name = 'Bathroom II';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Kitchen — Cook Breakfast', 'cooking', 45, '08:00',
  'Arrive ready. Leave it ready.

Week 1 sample breakfasts — Tropical Granola Smoothie Bowl · Quinoa Poke Bowl · Shakshuka Eggs on Toast · Berry Granola Smoothie Bowl · Avocado Eggs on Toast · Waffles.

Two-week meal plan rotates. Check the iPad for today.',
  ARRAY['Reference today''s menu on the iPad', 'Pull all ingredients from the pantry', 'Cook the breakfast', 'Plate for service', 'Wipe stove top and counters when done']::text[],
  1.34, 0.95, -0.71
from public.rooms r where r.name = 'The Kitchen';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Kitchen — Cook Dinner', 'cooking', 75, '18:00',
  'THE GOLDEN RULE — when you use a dish, put it in the dishwasher. If the dishwasher is full or running, wash it by hand. No third option. No "later."

Week 1 sample dinners: Burritos · Beef Bolognese · Chili Con Carne · Chicken and Potatoes · Beef Lasagna · Grilled Chicken Thighs · Burritos.',
  ARRAY['Reference today''s menu on the iPad', 'Pull all ingredients', 'Cook to plan', 'Plate for service', 'Clean every pot you used', 'Wipe steel counters and stove top', 'Clear the sink completely', 'Return all condiments and sauces to their shelves', 'Run / load the dishwasher', 'Spray the air freshener before you leave']::text[],
  1.34, 0.95, -0.71
from public.rooms r where r.name = 'The Kitchen';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Kitchen — Island Wipe-down', 'cleaning', 10, '14:00',
  'Never abandon a drink anywhere in the room. Never abandon a laptop on the island. Keep jackets and bags off all counters and chairs.',
  ARRAY['Clear everything off the island', 'Wipe the island top', 'Wipe the stools', 'Reset to bare surface']::text[],
  0, 0.95, 0.13
from public.rooms r where r.name = 'The Kitchen';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Kitchen — iPad Replenishment Sweep', 'supplies', 15, '21:00',
  'The iPad mounted at the entrance is the single source of truth for assets, the active replenishment list, and any voiced suggestions or comments.

ACTION                           TRIGGER
Find an item                     →  Reference the index on the iPad.
Item is finished                 →  Add it to the Items list and say "Hey Google Home, we are missing [item]."
Tool missing from its rack       →  Flag it on the iPad so the next user is not blocked.
Meal suggestion                  →  "Hey Google Home, add [meal] to the suggestions."',
  ARRAY['Open the iPad index', 'Check the active replenishment list', 'Voice each missing item to Google Home', 'Flag any missing tools on the iPad', 'Log any new meal suggestions']::text[],
  2.09, 1.05, 0.67
from public.rooms r where r.name = 'The Kitchen';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Hardware Lab — Workspaces Reset', 'cleaning', 8, '22:00',
  'Zone 01 — Workspaces. If you leave, dock your laptop. The desk is for the next user.',
  ARRAY['All laptops docked', 'All pens in their holders', 'Cables coiled', 'Desks cleared']::text[],
  0, 0.95, -0.97
from public.rooms r where r.name = 'Hardware Lab';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Hardware Lab — Pegboard Reset', 'cleaning', 10, '22:00',
  'Zone 02 — Pegboard. Every tool returns to its labelled silhouette. No exceptions.',
  ARRAY['Every tool returned to its silhouette', 'Pegboard fully populated', 'Loose hardware tidied']::text[],
  -0.87, 0.95, 0.44
from public.rooms r where r.name = 'Hardware Lab';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Hardware Lab — Repair Depot Sort', 'cleaning', 5, '22:00',
  'Broken? Drop it in the bin. Tag it with a sticker.

GREEN — Needs repair.  ORANGE — Try, else for parts.  RED — Parts only.',
  ARRAY['Each item tagged Green / Orange / Red', 'Bin lid closed', 'Loose parts bagged']::text[],
  0, 0.55, 1
from public.rooms r where r.name = 'Hardware Lab';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Tech Room — Tables match Silhouettes', 'supplies', 8, '21:00',
  'Three surfaces. Tables — colour-coded labels assign each peripheral to a specific table.',
  ARRAY['Peripherals match the colour-coded labels', 'Drones sit on their pegboard outlines', 'Printers sit on the shelf', 'Lens count matches the cabinet inventory']::text[],
  0, 0.95, -0.99
from public.rooms r where r.name = 'The Tech Room';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Tech Room — Cabinet Lock-up', 'supplies', 6, '21:00',
  'Lenses tracked against the inventory list inside the cabinet door. Cap each lens, lock the cabinet.',
  ARRAY['Lenses capped', 'Inventory list ticked against contents', 'Cabinet locked']::text[],
  1.52, 1.4, 0.64
from public.rooms r where r.name = 'The Tech Room';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Tech Room — Issue Book + Door Lock', 'supplies', 5, '21:00',
  'Anything missing or broken? Log it before you leave. One source of truth.

KNOWN FIXES — CANON paper jam: power off, open top, pull paper, check no scraps, power on. CANON streaks: nozzle check from touchscreen. CANON power-down: front panel only, never the wall switch. DJI NEO 2 protector on at start: power off, remove protector, power on.',
  ARRAY['Log anything missing or broken', 'Canon front-panel off (never the wall switch)', 'Cables coiled', 'Door locked']::text[],
  0, 1.1, 1.09
from public.rooms r where r.name = 'The Tech Room';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Gallery — Content Lounge Reset', 'cleaning', 8, '22:00',
  'Zone 01 — Content Lounge. Podcasting · filming · interviews · long-form content.',
  ARRAY['Mics returned to the wardrobe', 'Cameras and lighting returned', 'Backdrops folded and stored', 'Sofa cushions reset']::text[],
  -1.58, 0.95, -2.13
from public.rooms r where r.name = 'Gallery';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Gallery — Muse Mirror Reset', 'cleaning', 6, '22:00',
  'Zone 02 — Muse Mirror. Photography · styling · personal branding · social. On-station: lights and props ready to go.',
  ARRAY['Ring light powered off', 'Mirror clean', 'Props returned to the wardrobe']::text[],
  2.36, 0.95, -2.13
from public.rooms r where r.name = 'Gallery';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Gallery — Sound Salon Reset', 'cleaning', 6, '22:00',
  'Zone 03 — Sound Salon. Saxophone · guitar · kora · keyboard · vinyl. Handle with care.',
  ARRAY['Instruments returned home', 'Cables coiled', 'Vinyl back in its sleeve']::text[],
  2.63, 0.55, 1.91
from public.rooms r where r.name = 'Gallery';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Gallery — Wardrobe Full', 'supplies', 10, '23:00',
  'Take all you need before you start. By 22:00 the wardrobe is full — mics, cameras, lighting, backdrops back home.',
  ARRAY['Mics counted and home', 'Cameras counted and home', 'Lighting counted and home', 'Backdrops folded and home', 'No food, no bags']::text[],
  -3.55, 1.4, 0.56
from public.rooms r where r.name = 'Gallery';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Library — Morning Reset (Sleep → Work)', 'cleaning', 20, '09:00',
  '09:00–10:00 — Reset. Futons rolled · ornaments dusted · tatami swept · chabudai out · lamps on · fountain on. Duty pair.',
  ARRAY['Futons rolled', 'Ornaments dusted', 'Tatami swept', 'Chabudai out', 'Lamps on', 'Fountain on']::text[],
  0, 0.4, 0
from public.rooms r where r.name = 'Library';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Library — Sleep Prep (Meditation → Sleep)', 'cleaning', 15, '23:00',
  '23:00–00:00 — Sleep Prep. Cushions stored · futons rolled out · fountain off · last lantern dim · AC night mode. Silence returns.',
  ARRAY['Cushions stored', 'Futons rolled out', 'Fountain off', 'Last lantern dim', 'AC on night mode']::text[],
  0, 0.4, 0
from public.rooms r where r.name = 'Library';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Library — Cupboard V (Seasonal Clothing & Sewing)', 'supplies', 10, '10:00',
  'Every garment lives inside a fabric box. Every needle and pin lives inside a tin or case. Nothing loose.

Clothes on top · Sewing on the bottom. If a box is overfilled → redistribute into a second box.',
  ARRAY['Seasonal clothing in fabric boxes', 'Needles and pins cased', 'Fabric rolled or folded — no creases', 'Nothing damp or dirty stored']::text[],
  -0.92, 1.4, -1.04
from public.rooms r where r.name = 'Library';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Library — Laundry Round', 'laundry', 45, '11:00',
  'The Laundry is live 08:00 – 21:00. Five baskets: Towels & Beddings · Whites · Wool · Mixed · Underwear. A Mixed wash runs every morning. The evening load follows the weekly calendar.',
  ARRAY['Sort to baskets — Towels · Whites · Wool · Mixed · Underwear', 'Load the machine for today''s cycle', 'Run the cycle', 'Iron items that need it', 'Store on hanger in size order (larger above)', 'Machine unloaded · baskets returned to labels']::text[],
  0.92, 1.4, -1.04
from public.rooms r where r.name = 'Library';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Hallway — Sweep & Mop', 'cleaning', 10, '09:00',
  'Sweep first, mop second. Get the corners — that''s where it builds up.',
  ARRAY['Sweep the full length', 'Mop with diluted floor cleaner', 'Wipe skirting boards if smudged', 'Doormat shaken out']::text[],
  0, 0.35, 0
from public.rooms r where r.name = 'Hallway';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Closet — Tidy Shelves', 'supplies', 8, '10:00',
  'Front of shelf = always grabbable. Back of shelf = stock. Nothing on the floor.',
  ARRAY['Front-of-shelf items reachable', 'Like with like — group by type', 'Floor cleared', 'Door closes flush']::text[],
  0, 0.95, 0
from public.rooms r where r.name = 'Closet';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'Bathroom III — Sink & Toilet Zone', 'cleaning', 6, '09:00',
  'Small bathroom — single pass. Sink · toilet · floor · mirror. Done.',
  ARRAY['Sink rinsed and wiped', 'Toilet seat and bowl wiped', 'Floor mopped', 'Mirror streak-free']::text[],
  0, 0.95, 0
from public.rooms r where r.name = 'Bathroom III';

insert into public.task_templates
  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)
select
  r.id, 'War Room — End-of-day Reset', 'cleaning', 12, '22:00',
  'Close out the day. Clear the table, dock the laptops, kill the screens, log anything broken on the iPad.',
  ARRAY['Table cleared', 'Laptops docked', 'Screens powered off', 'Issues logged', 'Door closed']::text[],
  0, 0.95, 0
from public.rooms r where r.name = 'War Room';

-- One pending instance per template, scheduled for today at the template's time-of-day.
insert into public.task_instances (template_id, room_id, scheduled_for, status)
select t.id, t.room_id, (current_date::text || ' ' || t.schedule_time::text)::timestamptz, 'pending'
from public.task_templates t;

commit;
