// One-off generator: reads SEED_TEMPLATES from src/lib/data/seed.ts and
// prints SQL INSERTs that look up each room by name. Also generates one
// pending task_instance per template scheduled for today. Run with:
//
//   npx tsx scripts/generate_seed_sql.ts > supabase/seed_data.sql
//
// Then paste the result into the Supabase dashboard SQL editor.

import { SEED_TEMPLATES } from "../src/lib/data/seed";

// Map the local string room IDs used in seed.ts back to the room names
// inserted by 0001_initial_schema.sql, which is how we'll look them up.
const ROOM_NAME_BY_ID: Record<string, string> = {
  bathroom1: "Bathroom I",
  bathroom2: "Bathroom II",
  bathroom3: "Bathroom III",
  kitchen: "The Kitchen",
  hardwareLab: "Hardware Lab",
  techRoom: "The Tech Room",
  gallery: "Gallery",
  library: "Library",
  hallway: "Hallway",
  closet: "Closet",
  warroomServerHub: "War Room",
};

const sqlString = (s: string) => `'${s.replace(/'/g, "''")}'`;
const sqlArray = (arr: string[]) =>
  `ARRAY[${arr.map((s) => sqlString(s)).join(", ")}]::text[]`;

const lines: string[] = [
  "-- Auto-generated by scripts/generate_seed_sql.ts",
  "-- Inserts task_templates (one row per template in src/lib/data/seed.ts)",
  "-- and one pending task_instance per template for today.",
  "-- Idempotency: run this exactly once. Re-running will create duplicates.",
  "",
  "begin;",
  "",
];

for (const t of SEED_TEMPLATES) {
  const roomName = ROOM_NAME_BY_ID[t.room_id];
  if (!roomName) {
    lines.push(`-- SKIP ${t.id}: no room mapping for ${t.room_id}`);
    continue;
  }
  lines.push(
    "insert into public.task_templates",
    "  (room_id, name, category, duration_min, schedule_time, instructions, subtasks, pin_x, pin_y, pin_z)",
    "select",
    `  r.id, ${sqlString(t.name)}, ${sqlString(t.category)}, ${t.duration_min}, ${sqlString(t.schedule_time)},`,
    `  ${sqlString(t.instructions)},`,
    `  ${sqlArray(t.subtasks)},`,
    `  ${t.pin.x}, ${t.pin.y}, ${t.pin.z}`,
    `from public.rooms r where r.name = ${sqlString(roomName)};`,
    "",
  );
}

lines.push(
  "-- One pending instance per template, scheduled for today at the template's time-of-day.",
  "insert into public.task_instances (template_id, room_id, scheduled_for, status)",
  "select t.id, t.room_id, (current_date::text || ' ' || t.schedule_time::text)::timestamptz, 'pending'",
  "from public.task_templates t;",
  "",
  "commit;",
);

console.log(lines.join("\n"));
